name: devops test

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run:
          chmod +x ./gradlew
          ./gradlew build
    # - name: get code from github
    #   uses: appleboy/ssh-action@v1.0.3
    #   with:
    #     host: ${{ secrets.REMOTE_HOST }}
    #     username: ${{ secrets.REMOTE_USER }}
    #     key: ${{ secrets.SSH_KEY }}
    #     port: ${{ secrets.REMOTE_PORT }}
    #     script: |
    #       echo test > /tmp/abcd
